name: Validate Pull Request

on: pull_request

jobs:
  deploy:
    name: PR Validation
    uses: ./.github/workflows/deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: test
