name: Validate Pull Request

on: pull_request

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean install dependencies
        run: npm ci

      - name: Install AWS CDK
        run: npm i -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Synth stack
        run: cdk synth

      - name: Deploy stack
        run: cdk deploy
